In [24]:
import numpy as np
from scipy.io import loadmat

In [25]:
edge_density_matrices = np.array([
    loadmat("data/P_2_dogs3_drag-and-drop.mat")["P_2"] / i
    for i in range(1, 11)
])
observed_matrices = np.array([
    np.array([[2260, 1974, 2011], [1974, 1860, 1732], [2011, 1732, 1720]], dtype=int)
    for i in range(10)
])

In [26]:
edge_density_matrices.shape

(10, 3, 3)

In [27]:
avg_edge_density_matrix = np.average(edge_density_matrices, axis=0, weights=observed_matrices)

0.16547707158521302
0.04035863044981586
0.03218806484967599
0.04035863044981586
0.1250276000947643
0.046335871916125954
0.03218806484967599
0.046335871916125954
0.18018399039644367
[[0.16547707 0.04035863 0.03218806]
 [0.04035863 0.1250276  0.04633587]
 [0.03218806 0.04633587 0.18018399]]
