In [1]:
from analyzer import *
from glob import glob
from scipy.io import savemat
import re

In [2]:
mats = {"birds5": {},
 "dogs3": {}}
for filename in glob("./data/*-n=145.json"):
    dataset = "birds5" if "birds5" in filename else "dogs3"
    n_i = int(re.search("practice-[0-9]", filename).group(0)[-1])
    size = size_of_dataset(dataset)
    is_radio = "radio" in filename
    has_practice = True

    true_adj_matrix = retrieve_true_adj_matrix(dataset)
    true_clustering = retrieve_true_clustering(dataset)
    true_labels = retrieve_true_labels(dataset)

    np.random.seed(0)
    analyer = Analyzer(
        filename,
        size,
        true_adj_matrix(),
        dataset=dataset,
        radio=is_radio,
        practice=has_practice
    )

    c = analyer.edge_density(true_clustering())
    mats[dataset][n_i] = c

In [3]:
mats["dogs3"]

{7: array([[0.55638269, 0.14685535, 0.06889704],
        [0.14685535, 0.41785446, 0.1633175 ],
        [0.06889704, 0.1633175 , 0.70314788]]),
 6: array([[0.65233104, 0.10208167, 0.05099206],
        [0.10208167, 0.51082863, 0.15328467],
        [0.05099206, 0.15328467, 0.72024327]]),
 5: array([[0.68792402, 0.09412982, 0.05247884],
        [0.09412982, 0.5295858 , 0.12083677],
        [0.05247884, 0.12083677, 0.70869099]]),
 4: array([[0.62456345, 0.06295803, 0.0380291 ],
        [0.06295803, 0.50192456, 0.10426716],
        [0.0380291 , 0.10426716, 0.67911585]]),
 8: array([[0.55901211, 0.12752722, 0.05293711],
        [0.12752722, 0.40087719, 0.12783751],
        [0.05293711, 0.12783751, 0.66989382]]),
 2: array([[0.5045208 , 0.1352657 , 0.11445199],
        [0.1352657 , 0.35440181, 0.17281106],
        [0.11445199, 0.17281106, 0.55952381]]),
 3: array([[0.33818493, 0.09073265, 0.04588529],
        [0.09073265, 0.28855721, 0.09633803],
        [0.04588529, 0.09633803, 0.46448703]])}

In [7]:
print(mats["birds5"][2])

[[0.5648855  0.175      0.08679245 0.02962963 0.02264151 0.05309735]
 [0.175      0.50393701 0.44081633 0.03478261 0.05017921 0.03921569]
 [0.08679245 0.44081633 0.66666667 0.01680672 0.03797468 0.03139013]
 [0.02962963 0.03478261 0.01680672 0.74468085 0.06018519 0.06896552]
 [0.02264151 0.05017921 0.03797468 0.06018519 0.81343284 0.06451613]
 [0.05309735 0.03921569 0.03139013 0.06896552 0.06451613 0.13793103]]


In [20]:
mapping = {
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: 'seven',
    8: "eight"
}

In [25]:
new_mats = {}
for key in mats.keys():
    new_mats[key] = {}
    for _key in mats[key].keys():
        new_mats[key][key + "_" + str(_key)]  = mats[key][_key]

In [26]:
savemat("birds5_empirical_edge_density.mat", new_mats["birds5"])

In [27]:
savemat("dogs3_empirical_edge_density.mat", new_mats["dogs3"])

In [28]:
new_mats["dogs3"]

{'dogs3_7': array([[0.55638269, 0.14685535, 0.06889704],
        [0.14685535, 0.41785446, 0.1633175 ],
        [0.06889704, 0.1633175 , 0.70314788]]),
 'dogs3_6': array([[0.65233104, 0.10208167, 0.05099206],
        [0.10208167, 0.51082863, 0.15328467],
        [0.05099206, 0.15328467, 0.72024327]]),
 'dogs3_5': array([[0.68792402, 0.09412982, 0.05247884],
        [0.09412982, 0.5295858 , 0.12083677],
        [0.05247884, 0.12083677, 0.70869099]]),
 'dogs3_4': array([[0.62456345, 0.06295803, 0.0380291 ],
        [0.06295803, 0.50192456, 0.10426716],
        [0.0380291 , 0.10426716, 0.67911585]]),
 'dogs3_8': array([[0.55901211, 0.12752722, 0.05293711],
        [0.12752722, 0.40087719, 0.12783751],
        [0.05293711, 0.12783751, 0.66989382]]),
 'dogs3_2': array([[0.5045208 , 0.1352657 , 0.11445199],
        [0.1352657 , 0.35440181, 0.17281106],
        [0.11445199, 0.17281106, 0.55952381]]),
 'dogs3_3': array([[0.33818493, 0.09073265, 0.04588529],
        [0.09073265, 0.28855721, 0.09

In [16]:
from scipy.io import loadmat

In [17]:
m = loadmat('./mats/radio-2-image-dogs3-2023.mat')

In [18]:
m['adjacency_matrix']

array([[ 1, -1, -1, ..., -1, -1, -1],
       [-1,  1, -1, ..., -1, -1, -1],
       [-1, -1,  1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ...,  1, -1, -1],
       [-1, -1, -1, ..., -1,  1, -1],
       [-1, -1, -1, ..., -1, -1,  1]])

In [15]:
np.unique(m['adjacency_frequency_matrix'])

array([-1,  0,  1,  2,  3])

In [19]:
m['adjacency_matrix']

array([[ 1, -1, -1, ..., -1, -1, -1],
       [-1,  1, -1, ..., -1, -1, -1],
       [-1, -1,  1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ...,  1, -1, -1],
       [-1, -1, -1, ..., -1,  1, -1],
       [-1, -1, -1, ..., -1, -1,  1]])

In [21]:
m['observation_matrix'].sum()

17799

In [22]:
m['observation_matrix'].shape

(473, 473)